### PR TITLE
cedric: Update WFD blobs from LA.UM.8.6.r1-01900-89xx.0

### PR DESCRIPTION
**Pull request by zjunior06**
* This fix WifiDisplay (Miracast)

Signed-off-by: ZJRDroid <priv.zjr@gmail.com>

### CODE REVIEW

**Comment by mvaisakh** [comment]
Which device is this from?

**Comment by mvaisakh** [comment]
And is this tested?

**Comment by zjunior06** [comment]
tested and working fully

**Comment by zjunior06** [comment]
Taken from: https://github.com/PixelExperience-Devices/vendor_motorola/commit/a4540fff1dd9f123aecc7f692f1d34570da02cd3

**Pull request merged**
